#!/usr/bin/env bash
set -euo pipefail

cd /var/www/vacode.org

chown -R www-data:ubuntu .
chmod -R g+w .

mkdir -p htdocs/downloads htdocs/content

# The importer's environment test requires sitemap.xml to exist and be writable
# before it will import anything, but the file is generated by the import itself
# (generate_sitemap) and is gitignored upstream, so it is absent from a fresh
# deploy. is_writable() is false for a missing file, so without this the test
# fails, ImportAction skips the whole import, and the CLI still exits 0. Create
# an empty placeholder for the import to overwrite. These run after the
# recursive chown above, so set ownership explicitly.
touch htdocs/sitemap.xml
chown www-data:ubuntu htdocs/sitemap.xml
chmod 664 htdocs/sitemap.xml

# The importer reads from IMPORT_DATA_DIR, which sits outside the webroot and
# outside this bundle so the updater's scraped XML survives deploys. Absolute
# path deliberately: it is not part of the deployed tree, so the recursive
# chown above does not reach it.
#
# Ownership is ubuntu, the inverse of the app tree: updater.sh runs from
# ubuntu's crontab and rsyncs into this directory, and rsync -a (which implies
# -t) sets mtime on the destination directory itself. That requires ownership --
# utimensat() returns EPERM unless the effective UID matches the owner, so group
# write is not sufficient.
#
# Only the ownership set here persists. rsync -a also implies -p, so the mode
# and group below are replaced on each run by those of the scraper's output
# directory (0755 under ubuntu's umask). That is what lets www-data, which only
# ever reads these files, still traverse the directory and read the 0644 XML.
mkdir -p /var/www/vacode.org/import-data
chown ubuntu:www-data /var/www/vacode.org/import-data
chmod 755 /var/www/vacode.org/import-data

# Ensure the updater is executable: the zip → CodeDeploy round trip does not
# reliably preserve the execute bit, and cron invokes this script directly.
chmod +x updater.sh

# Restore the preserved API_KEY value into the freshly-deployed config.
api_key=""
if [ -f /tmp/api_key ]; then
    api_key=$(cat /tmp/api_key)
    rm -f /tmp/api_key
fi
sed -i "s|__API_KEY__|${api_key}|" includes/config.inc.php

# Restrict config so credentials aren't world-readable
chmod 640 includes/config.inc.php

# Install the updater's schedule into the ubuntu user's crontab. Idempotent: our
# own managed lines (the updater entries and the MAILTO we set) are stripped and
# re-added, so schedule changes made in this script take effect on the next
# deploy, while any unrelated entries are preserved.
existing=$(sudo -u ubuntu crontab -l 2>/dev/null \
    | grep -vE '/var/www/vacode.org/updater.sh|^MAILTO=waldo@jaquith\.org' || true)
{
    if [ -n "$existing" ]; then
        printf '%s\n' "$existing"
    fi
    # Mail any cron-level failure of the updater jobs (e.g., a missing or
    # non-executable script). The script redirects its own output to the log.
    echo 'MAILTO=waldo@jaquith.org'
    echo '0 2 2 1-6,8-12 * /var/www/vacode.org/updater.sh'
    echo '0 2 2 7 * /var/www/vacode.org/updater.sh --new-edition'
} | sudo -u ubuntu crontab -

# Rotate the updater's log so it doesn't grow without bound. This script runs as
# root, so it can write to /etc/logrotate.d.
cp .github/deploy/logrotate-vacode /etc/logrotate.d/vacode
chmod 644 /etc/logrotate.d/vacode
